import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Libre_Franklin } from "next/font/google";
import { Chivo } from "next/font/google";
import { Header } from "@/components/component/header";

const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  display: "swap",
});

const chivo = Chivo({
  subsets: ["latin"],
  display: "swap",
});

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
  display: "swap",
  variable: "--font-bebas",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre_franklin.className} ${bebas.variable} ${montserrat.className}  `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
