import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Libre_Franklin } from "next/font/google";
import { Chivo } from "next/font/google";
import { Header } from "@/components/component/header";
import { Bg } from "@/components/animations/bg";

const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  display: "swap",
});

const chivo = Chivo({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libre_franklin.className}  `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
